# Generated by Django 2.2.19 on 2023-05-20 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                        ],
                        default=2023,
                        verbose_name="Год",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        default=5,
                        verbose_name="Месяц",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бухгалтерия",
                "verbose_name_plural": "Бухгалтерии",
                "ordering": ("year", "month"),
            },
        ),
        migrations.CreateModel(
            name="СategoryExpense",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория расхода",
                "verbose_name_plural": "Категории расходов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="СategoryIncome",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория дохода",
                "verbose_name_plural": "Категории доходов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="IncomeCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.IntegerField(verbose_name="Сумма")),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_categories",
                        to="accounts.СategoryIncome",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "incomes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_incomes",
                        to="accounts.Accounting",
                        verbose_name="Доход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчет доходов",
                "verbose_name_plural": "Расчеты доходов",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ExpenseCalculation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.IntegerField(verbose_name="План")),
                ("sum", models.IntegerField(verbose_name="Сумма")),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_categories",
                        to="accounts.СategoryExpense",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "expenses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation_expense",
                        to="accounts.Accounting",
                        verbose_name="Доход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчет расходов",
                "verbose_name_plural": "Расчеты расходов",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="accounting",
            name="expense",
            field=models.ManyToManyField(
                related_name="accounting_expense",
                through="accounts.ExpenseCalculation",
                to="accounts.СategoryExpense",
                verbose_name="Расход",
            ),
        ),
        migrations.AddField(
            model_name="accounting",
            name="incomes",
            field=models.ManyToManyField(
                related_name="accounting_incomes",
                through="accounts.IncomeCalculation",
                to="accounts.СategoryIncome",
                verbose_name="Доход",
            ),
        ),
        migrations.AddField(
            model_name="accounting",
            name="users",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounting_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomecalculation",
            constraint=models.UniqueConstraint(
                fields=("incomes", "categories"), name="unique_income"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensecalculation",
            constraint=models.UniqueConstraint(
                fields=("expenses", "categories"), name="unique_expense"
            ),
        ),
        migrations.AddConstraint(
            model_name="accounting",
            constraint=models.UniqueConstraint(
                fields=("users", "year", "month"), name="unique_accounting"
            ),
        ),
    ]
