# Generated by Django 2.2.19 on 2023-05-22 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounting",
            options={
                "ordering": ("-year", "-month"),
                "verbose_name": "Бухгалтерия",
                "verbose_name_plural": "Бухгалтерии",
            },
        ),
        migrations.AlterModelOptions(
            name="expensecalculation",
            options={
                "ordering": ("categories__id",),
                "verbose_name": "Расчет расходов",
                "verbose_name_plural": "Расчеты расходов",
            },
        ),
        migrations.AlterModelOptions(
            name="incomecalculation",
            options={
                "ordering": ("categories__id",),
                "verbose_name": "Расчет доходов",
                "verbose_name_plural": "Расчеты доходов",
            },
        ),
    ]
